### ISSUE TITLE
Main page proportions between the strips

### ISSUE THREAD

**Issue by Razielt77** [codefresh-io/blog#10]
Hi, I am attaching screenshot I took with comments and also the original image for reference

![comments1](https://cloud.githubusercontent.com/assets/7720348/8273627/0dbd7b12-182b-11e5-8edc-bb549a8443cd.png)
![comments1_org](https://cloud.githubusercontent.com/assets/7720348/8273630/1164f77c-182b-11e5-86b6-21cb44fd2f58.png)

**Comment by tgolen** [comment]
I originally had that header image spread across the whole screen and you said you didn't like it (it did funky things with the new height of the header). I can revert those changes and try increasing the height of the header to compensate, but I can tell you it's still not going to work because of varying browser widths.

I will fix the margin at the top of the blog posts and the size of the font for the post excerpts. 

As for the size of the post images, I am not sure what to recommend. If you want a more consistent size, then you will have to sacrifice the visible edges of the image. In other words, I would make the container an absolute size (say 100x200) and make the height of the image match the height of the container, then center the image in the background. If you had a very wide image (say 100x400), then it would cut off 100px from each side of the image.

**Comment by Razielt77** [comment]
ok. let try to increase the height of the header. I wonder if the solution is not to threat the container in the header as objects rather than 1 background image. then you can position them and move them around based the screen size. wouldn't that be give the better outcome?

**Comment by Razielt77** [comment]
So the image is positioned well now for the 1section. the only comment left is to position the text in the mid of the screen (vertically)

What's hasn't changed is the comments per the 2nd strip (where the post are)
 - Can we add more space before and after the post like in the 2nd attachment in this issue.
- Can we increase the size of the fonts on this section. currently the font are even smaller than the fonts in the footer.

**Comment by tgolen** [comment]
I have increased the padding on the top of the blog title to provide better vertical alignment (which isn't really a thing that you can do with multi-line text without using JS).

I have added more space before and after the post.

I have increased the font size of the post excerpts.
